services:
  - type: web
    name: mushroom-lora-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.api
    envVars:
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "10000"
      - key: RELOAD
        value: "false"
      - key: PYTHONPATH
        value: "/opt/render/project/src"