services:
  - type: web
    name: mushroom-lora-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: "/opt/render/project/src"